### ISSUE TITLE
Molly vagrant hanging on some counter example suite tests.

### ISSUE THREAD

**Issue by KDahlgren** [palvaro/molly#12]
Hi, 

I'm working with Molly via the vagrant image on OS X High Sierra.
I was running through the counter example test suite manually and noticed a few tests seem to hang, sometimes as a result of running out of memory. I'm just running the vagrant file with whatever additional virtual system defaults are provided in vagrant. 

The attached image shows the error encountered when running 
sbt "run-main edu.berkeley.cs.boom.molly.SyncFTChecker src/test/resources/examples_ft/commit/2pc.ded src/test/resources/examples_ft/commit/2pc_assert.ded --EOT 7 --EFF 3 --nodes a,b,C,d --crashes 0 --prov-diagrams"

The terminal just hangs until I control-c.

The behavior occurs on other tests as well. Has anyone else encountered this issue?

Best,
KD

<img width="830" alt="screen shot 2018-05-08 at 12 40 07 pm" src="https://user-images.githubusercontent.com/16612428/39779383-e0d6e9b4-52bd-11e8-85cd-5f0fdb90f273.png">

**Comment by palvaro** [comment]
did you try running it without the prov-diagrams flag?

**Comment by KDahlgren** [comment]
Nope, I didn't try that. 
Just ran all the stalling tests w/o prov-diagrams and got the results.
Thanks Peter!
